-- Create conversation_analytics table for business intelligence
CREATE TABLE IF NOT EXISTS conversation_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number VARCHAR(20) NOT NULL,
  search_keyword TEXT NOT NULL,
  result_count INTEGER NOT NULL DEFAULT 0,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  converted BOOLEAN DEFAULT FALSE,
  response_time_ms INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_conversation_analytics_phone_number ON conversation_analytics(phone_number);
CREATE INDEX IF NOT EXISTS idx_conversation_analytics_timestamp ON conversation_analytics(timestamp);
CREATE INDEX IF NOT EXISTS idx_conversation_analytics_keyword ON conversation_analytics(search_keyword);
CREATE INDEX IF NOT EXISTS idx_conversation_analytics_converted ON conversation_analytics(converted);

-- Add RLS (Row Level Security)
ALTER TABLE conversation_analytics ENABLE ROW LEVEL SECURITY;

-- Create policy for read access (you can customize based on your needs)
CREATE POLICY "Enable read access for all users" ON conversation_analytics
  FOR SELECT USING (true);

-- Create policy for insert access (for the webhook/API)
CREATE POLICY "Enable insert for service role" ON conversation_analytics
  FOR INSERT WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE conversation_analytics IS 'Analytics table for tracking WhatsApp conversation performance and user behavior';
COMMENT ON COLUMN conversation_analytics.phone_number IS 'Customer phone number (masked/pseudonymized for privacy)';
COMMENT ON COLUMN conversation_analytics.search_keyword IS 'The keyword extracted from customer message';
COMMENT ON COLUMN conversation_analytics.result_count IS 'Number of inventory items returned for the search';
COMMENT ON COLUMN conversation_analytics.converted IS 'Whether the search resulted in a successful conversion (found items)';
COMMENT ON COLUMN conversation_analytics.response_time_ms IS 'Time taken to process and respond to the message';
